services:
  - type: web
    name: saree-tryon
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python download_models.py"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120"
